const fs = require('fs');
const path = require('path');
require('dotenv').config();

const targetPath = path.join(__dirname, 'src/environments/environment.prod.ts');

// Security check: Ensure we don't accidentally leak "undefined" strings to production
const firebaseConfig = {
    apiKey: process.env.FIREBASE_API_KEY || "YOUR_API_KEY",
    authDomain: process.env.FIREBASE_AUTH_DOMAIN || "YOUR_PROJECT_ID.firebaseapp.com",
    projectId: process.env.FIREBASE_PROJECT_ID || "YOUR_PROJECT_ID",
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "YOUR_PROJECT_ID.appspot.com",
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "YOUR_SENDER_ID",
    appId: process.env.FIREBASE_APP_ID || "YOUR_APP_ID"
};

const envConfigFile = `// This file is automatically generated by set-env.js during build
export const environment = {
    production: true,
    firebase: ${JSON.stringify(firebaseConfig, null, 4)}
};
`;

console.log('--- Environment Configuration ---');
if (!process.env.FIREBASE_API_KEY) {
    console.warn('⚠️ WARNING: FIREBASE_API_KEY is not set. Deployment might fail to connect to Database.');
} else {
    console.log('✅ Firebase Environment Variables detected.');
}

fs.writeFileSync(targetPath, envConfigFile);
console.log(`Generated production environment file at ${targetPath}`);
console.log('---------------------------------');
